In [1]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2f7c76e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1D array: [1 2 3 4 5]\n",
      "2D array:\n",
      " [[1 2 3]\n",
      " [4 5 6]]\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "arr1 = np.array([1, 2, 3, 4, 5])\n",
    "print(\"1D array:\", arr1)\n",
    "arr2 = np.array([[1, 2, 3], [4, 5, 6]])\n",
    "print(\"2D array:\\n\", arr2)\n",
    "arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "0debc980",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Zeros array:\n",
      " [[0. 0. 0.]\n",
      " [0. 0. 0.]]\n",
      "Ones array:\n",
      " [[1. 1.]\n",
      " [1. 1.]\n",
      " [1. 1.]]\n",
      "Full array:\n",
      " [[7 7]\n",
      " [7 7]]\n",
      "Identity matrix:\n",
      " [[1. 0. 0. 0.]\n",
      " [0. 1. 0. 0.]\n",
      " [0. 0. 1. 0.]\n",
      " [0. 0. 0. 1.]]\n"
     ]
    }
   ],
   "source": [
    "zeros_arr = np.zeros((2, 3))\n",
    "print(\"Zeros array:\\n\", zeros_arr)\n",
    "\n",
    "ones_arr = np.ones((3, 2))\n",
    "print(\"Ones array:\\n\", ones_arr)\n",
    "\n",
    "full_arr = np.full((2, 2), 7)\n",
    "print(\"Full array:\\n\", full_arr)\n",
    "\n",
    "identity_arr = np.eye(4)\n",
    "print(\"Identity matrix:\\n\", identity_arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "67052f7b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "arange array: [0 2 4 6 8]\n",
      "linspace array: [0.   0.25 0.5  0.75 1.  ]\n",
      "Random float array:\n",
      " [[0.69174236 0.85419825 0.97017316]\n",
      " [0.86355654 0.05321901 0.61912007]]\n",
      "Random integer array:\n",
      " [[34 83 58]\n",
      " [42 12 81]]\n"
     ]
    }
   ],
   "source": [
    "range_arr = np.arange(0, 10, 2)  \n",
    "print(\"arange array:\", range_arr)\n",
    "\n",
    "lin_arr = np.linspace(0, 1, 5)   \n",
    "print(\"linspace array:\", lin_arr)\n",
    "\n",
    "rand_arr = np.random.rand(2, 3)      \n",
    "randint_arr = np.random.randint(1, 100, size=(2, 3))  \n",
    "print(\"Random float array:\\n\", rand_arr)\n",
    "print(\"Random integer array:\\n\", randint_arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "868c5940",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[0. 0. 0. 0.]\n",
      " [0. 0. 0. 0.]\n",
      " [0. 0. 0. 0.]\n",
      " [0. 0. 0. 0.]]\n",
      "[10 15 20 25 30 35 40 45 50]\n"
     ]
    }
   ],
   "source": [
    "exercise1_a = np.zeros((4, 4))\n",
    "exercise1_b = np.arange(10, 51, 5)\n",
    "print(exercise1_a)\n",
    "print(exercise1_b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d32518ee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Array:\n",
      " [[1 2 3]\n",
      " [4 5 6]]\n",
      "Shape: (2, 3)\n",
      "Dimensions: 2\n",
      "Size: 6\n",
      "Data type: int64\n"
     ]
    }
   ],
   "source": [
    "sample = np.array([[1, 2, 3], [4, 5, 6]])\n",
    "\n",
    "print(\"Array:\\n\", sample)\n",
    "print(\"Shape:\", sample.shape)      \n",
    "print(\"Dimensions:\", sample.ndim) \n",
    "print(\"Size:\", sample.size)        \n",
    "print(\"Data type:\", sample.dtype)  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "954f5b00",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reshaped (3x2):\n",
      " [[1 2]\n",
      " [3 4]\n",
      " [5 6]]\n",
      "Flattened: [1 2 3 4 5 6]\n",
      "Transpose:\n",
      " [[1 4]\n",
      " [2 5]\n",
      " [3 6]]\n"
     ]
    }
   ],
   "source": [
    "reshaped = sample.reshape(3, 2)   \n",
    "print(\"Reshaped (3x2):\\n\", reshaped)\n",
    "\n",
    "flat = sample.flatten()\n",
    "print(\"Flattened:\", flat)\n",
    "\n",
    "print(\"Transpose:\\n\", sample.T)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9a7fa7ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Concatenated: [1 2 3 4 5 6]\n",
      "Vertical stack:\n",
      " [[1 2 3]\n",
      " [4 5 6]]\n",
      "Horizontal stack: [1 2 3 4 5 6]\n"
     ]
    }
   ],
   "source": [
    "a = np.array([1, 2, 3])\n",
    "b = np.array([4, 5, 6])\n",
    "\n",
    "joined = np.concatenate((a, b))\n",
    "print(\"Concatenated:\", joined)\n",
    "\n",
    "stacked_v = np.vstack((a, b))   \n",
    "stacked_h = np.hstack((a, b))  \n",
    "print(\"Vertical stack:\\n\", stacked_v)\n",
    "print(\"Horizontal stack:\", stacked_h)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7ae7009a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original: [5 2 9 1 7]\n",
      "Sorted: [1 2 5 7 9]\n"
     ]
    }
   ],
   "source": [
    "unsorted = np.array([5, 2, 9, 1, 7])\n",
    "sorted_arr = np.sort(unsorted)\n",
    "print(\"Original:\", unsorted)\n",
    "print(\"Sorted:\", sorted_arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "bf222662",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shape: (2, 3)\n",
      "Size: 6\n",
      "Reshaped:\n",
      " [[1 2]\n",
      " [3 4]\n",
      " [5 6]]\n"
     ]
    }
   ],
   "source": [
    "ex2 = np.array([[1, 2, 3], [4, 5, 6]])\n",
    "print(\"Shape:\", ex2.shape)\n",
    "print(\"Size:\", ex2.size)\n",
    "print(\"Reshaped:\\n\", ex2.reshape(3, 2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "dcbb9705",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Addition: [11 22 33 44]\n",
      "Subtraction: [ 9 18 27 36]\n",
      "Multiplication: [ 10  40  90 160]\n",
      "Division: [10. 10. 10. 10.]\n",
      "Power: [ 100  400  900 1600]\n"
     ]
    }
   ],
   "source": [
    "x = np.array([10, 20, 30, 40])\n",
    "y = np.array([1, 2, 3, 4])\n",
    "\n",
    "print(\"Addition:\", x + y)\n",
    "print(\"Subtraction:\", x - y)\n",
    "print(\"Multiplication:\", x * y)\n",
    "print(\"Division:\", x / y)\n",
    "print(\"Power:\", x ** 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "65a8b229",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sum: 108\n",
      "Mean: 18.0\n",
      "Minimum: 4\n",
      "Maximum: 42\n",
      "Standard deviation: 12.315302134607444\n",
      "Variance: 151.66666666666666\n"
     ]
    }
   ],
   "source": [
    "data = np.array([4, 8, 15, 16, 23, 42])\n",
    "\n",
    "print(\"Sum:\", np.sum(data))\n",
    "print(\"Mean:\", np.mean(data))\n",
    "print(\"Minimum:\", np.min(data))\n",
    "print(\"Maximum:\", np.max(data))\n",
    "print(\"Standard deviation:\", np.std(data))\n",
    "print(\"Variance:\", np.var(data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "6d0d0c5a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Square root: [1. 2. 3. 4.]\n",
      "Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]\n",
      "Natural log: [0.         1.38629436 2.19722458 2.77258872]\n",
      "Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]\n"
     ]
    }
   ],
   "source": [
    "nums = np.array([1, 4, 9, 16])\n",
    "\n",
    "print(\"Square root:\", np.sqrt(nums))\n",
    "print(\"Exponential:\", np.exp(nums))\n",
    "print(\"Natural log:\", np.log(nums))\n",
    "print(\"Sine:\", np.sin(nums))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d814cfa9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Element-wise multiplication:\n",
      " [[ 5 12]\n",
      " [21 32]]\n",
      "Matrix multiplication (dot):\n",
      " [[19 22]\n",
      " [43 50]]\n",
      "Matrix multiplication (matmul):\n",
      " [[19 22]\n",
      " [43 50]]\n"
     ]
    }
   ],
   "source": [
    "m1 = np.array([[1, 2], [3, 4]])\n",
    "m2 = np.array([[5, 6], [7, 8]])\n",
    "\n",
    "print(\"Element-wise multiplication:\\n\", m1 * m2)\n",
    "print(\"Matrix multiplication (dot):\\n\", np.dot(m1, m2))\n",
    "print(\"Matrix multiplication (matmul):\\n\", np.matmul(m1, m2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "95ad2d4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sum: [ 3  7 11 15 19]\n",
      "Product: [ 2 12 30 56 90]\n",
      "Mean of sum: 11.0\n"
     ]
    }
   ],
   "source": [
    "p = np.array([2, 4, 6, 8, 10])\n",
    "q = np.array([1, 3, 5, 7, 9])\n",
    "\n",
    "ex3_sum = p + q\n",
    "ex3_product = p * q\n",
    "print(\"Sum:\", ex3_sum)\n",
    "print(\"Product:\", ex3_product)\n",
    "print(\"Mean of sum:\", np.mean(ex3_sum))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "4d9c042b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Full array: [10 20 30 40 50 60]\n",
      "First element: 10\n",
      "Last element: 60\n",
      "Elements from index 1 to 3: [20 30 40]\n",
      "Every second element: [10 30 50]\n",
      "Reversed array: [60 50 40 30 20 10]\n"
     ]
    }
   ],
   "source": [
    "arr = np.array([10, 20, 30, 40, 50, 60])\n",
    "\n",
    "print(\"Full array:\", arr)\n",
    "print(\"First element:\", arr[0])\n",
    "print(\"Last element:\", arr[-1])\n",
    "print(\"Elements from index 1 to 3:\", arr[1:4])\n",
    "print(\"Every second element:\", arr[::2])\n",
    "print(\"Reversed array:\", arr[::-1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "8efa51f7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Matrix:\n",
      " [[1 2 3]\n",
      " [4 5 6]\n",
      " [7 8 9]]\n",
      "Element at row 1, col 2: 6\n",
      "First row: [1 2 3]\n",
      "First column: [1 4 7]\n",
      "Sub-matrix (rows 0-1, cols 1-2):\n",
      " [[2 3]\n",
      " [5 6]]\n"
     ]
    }
   ],
   "source": [
    "matrix = np.array([[1, 2, 3],\n",
    "                    [4, 5, 6],\n",
    "                    [7, 8, 9]])\n",
    "\n",
    "print(\"Matrix:\\n\", matrix)\n",
    "print(\"Element at row 1, col 2:\", matrix[1, 2])\n",
    "print(\"First row:\", matrix[0, :])\n",
    "print(\"First column:\", matrix[:, 0])\n",
    "print(\"Sub-matrix (rows 0-1, cols 1-2):\\n\", matrix[0:2, 1:3])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}


{'cells': [{'cell_type': 'code',
   'execution_count': 3,
   'id': '2f7c76e2',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['1D array: [1 2 3 4 5]\n',
      '2D array:\n',
      ' [[1 2 3]\n',
      ' [4 5 6]]\n']}],
   'source': ['import numpy as np\n',
    'arr1 = np.array([1, 2, 3, 4, 5])\n',
    'print("1D array:", arr1)\n',
    'arr2 = np.array([[1, 2, 3], [4, 5, 6]])\n',
    'print("2D array:\\n", arr2)\n',
    'arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])\n',
    '\n']},
  {'cell_type': 'code',
   'execution_count': 4,
   'id': '0debc980',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['Zeros array:\n',
      ' [[0. 0. 0.]\n',
      ' [0. 0. 0.]]\n',
      'Ones array:\n',
      ' [[1. 1.]\n',
      ' [1. 1.]\n',
      ' [1. 1.]]\n',
      'Full array:\n',
      ' [[7 7]\n',
      ' [7 7]]\n',
      'Identity matrix:\n',
      ' [[1. 0. 0. 0.]\n',
      ' [0. 1. 0. 0.]\